version: 1
author: Fish-Face
language: Zig
dockerfile: .docker/Dockerfile
persistence:
  - /root/.cache/
  - /root/.local/
  - /code/.zig-cache
code: /code
workdir: /code
runonce: zig build --release=fast install_day%zeroday%
cmd: zig-out/bin/day%zeroday% inputs/%zeroday%.txt
daypath: src/%zeroday%.zig
inputfile: inputs/%zeroday%.txt
answerfile: answers/%zeroday%.txt
common:
  - common